services:
  idevice:
    image: ghcr.io/luca910/idevice-backuptool:main
    container_name: idevice
    stdin_open: true
    privileged: true
    network_mode: host
    tty: true
    volumes:
      - /run/udev:/run/udev:ro
      - /var/run/dbus:/var/run/dbus:ro
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket:ro
      - /dev/bus/usb:/dev/bus/usb

    #Persistence
      - /mnt/SSD/docker/idevice/lockdown:/var/lib/lockdown
      - /mnt/SSD/docker/idevice/backups:/mnt/backups
