[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:avahi-daemon]
command=/usr/sbin/avahi-daemon --no-drop-root
autostart=true
autorestart=true
stderr_logfile=/var/log/avahi-daemon.err.log
stdout_logfile=/var/log/avahi-daemon.out.log

[program:usbmuxd]
command=/usr/sbin/usbmuxd -f -s
autostart=true
autorestart=true
stderr_logfile=/var/log/usbmuxd.err.log
stdout_logfile=/var/log/usbmuxd.out.log
